plugins {
  id 'java-library'
  id 'maven-publish'
}

group = 'me.hanju.fluxhandle'
version = '0.4.2'
description = 'A reactive stream wrapper providing synchronous result access, cancellation, and streaming callbacks'

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
  withSourcesJar()
  withJavadocJar()
}

repositories {
  mavenCentral()
  maven { url 'https://jitpack.io' }
}

dependencies {
  implementation 'org.slf4j:slf4j-api:2.0.17'

  api 'io.projectreactor:reactor-core:3.8.1'
  api 'com.github.agent-hanju:streambind:0.1.0'

  testImplementation 'org.junit.jupiter:junit-jupiter:6.0.1'
  testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
  testRuntimeOnly 'ch.qos.logback:logback-classic:1.5.22'
  testCompileOnly 'org.projectlombok:lombok:1.18.42'
  testAnnotationProcessor 'org.projectlombok:lombok:1.18.42'
}

tasks.withType(JavaCompile).configureEach {
  options.encoding = 'UTF-8'
}

tasks.withType(Javadoc).configureEach {
  options.encoding = 'UTF-8'
  options.charSet = 'UTF-8'
  failOnError = false
}

tasks.named('test') {
  useJUnitPlatform()
  systemProperty 'file.encoding', 'UTF-8'
}

publishing {
  publications {
    mavenJava(MavenPublication) {
      from components.java

      pom {
        name = 'fluxhandle'
        description = project.description
        url = 'https://github.com/agent-hanju/fluxhandle'
        inceptionYear = '2026'

        licenses {
          license {
            name = 'MIT License'
            url = 'https://opensource.org/licenses/MIT'
            distribution = 'repo'
          }
        }

        developers {
          developer {
            id = 'agent-hanju'
            name = 'hanju'
            email = 'agent.hanju@gmail.com'
          }
        }

        scm {
          url = 'https://github.com/agent-hanju/fluxhandle'
          connection = 'scm:git:git://github.com/agent-hanju/fluxhandle.git'
          developerConnection = 'scm:git:ssh://git@github.com/agent-hanju/fluxhandle.git'
        }

        issueManagement {
          system = 'GitHub Issues'
          url = 'https://github.com/agent-hanju/fluxhandle/issues'
        }
      }
    }
  }
}
